# Generated by Django 4.1.1 on 2022-11-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authorname', models.CharField(max_length=100)),
                ('AuthorBio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Genere', models.CharField(max_length=100)),
                ('PublishDate', models.CharField(max_length=4)),
                ('Publisher', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CopiesSold', models.IntegerField()),
                ('AvgRating', models.IntegerField()),
                ('Description', models.TextField()),
                ('AuthorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_detail', to='browsing.authors')),
            ],
            options={
                'ordering': ['Isbn'],
            },
        ),
    ]
